#!/usr/bin/env python3
"""
Simple map publisher — waits for PGM+YAML, then publishes OccupityGrid at 2 Hz.
Replaces nav2_map_server (which requires lifecycle activation) for our use case.

Starts immediately; retries until the map file exists (generated by spawn_obstacles).
"""
import sys
import os
import time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
from PIL import Image
import yaml

from ros_compat import CompatNode, spin, OccupancyGrid


class MapPublisher:
    def __init__(self, node):
        self.node = node

        node.declare_parameter('yaml_filename', '')
        yaml_path = node.get_parameter('yaml_filename')
        node.loginfo("Waiting for map YAML: %s", yaml_path)

        # Wait for the YAML file to exist (generated by spawn_obstacles)
        while CompatNode.ok():
            if yaml_path and os.path.exists(yaml_path):
                break
            node.loginfo("Map file not ready yet, retrying in 2s...")
            time.sleep(2)

        # Load YAML
        with open(yaml_path, 'r') as f:
            map_config = yaml.safe_load(f)

        pgm_path = map_config['image']
        resolution = map_config['resolution']
        origin = map_config['origin']

        # Resolve relative PGM path
        if not os.path.isabs(pgm_path):
            pgm_path = os.path.join(os.path.dirname(yaml_path),
                                    os.path.basename(pgm_path))

        node.loginfo("Waiting for fresh PGM: %s", pgm_path)

        # Record initial mtime — wait for spawn_obstacles to UPDATE the file
        initial_mtime = os.path.getmtime(pgm_path) if os.path.exists(pgm_path) else 0
        while CompatNode.ok():
            if os.path.exists(pgm_path) and os.path.getmtime(pgm_path) > initial_mtime:
                break
            node.loginfo("PGM not updated yet, retrying in 2s...")
            time.sleep(2)

        # Load PGM image
        img = Image.open(pgm_path)
        map_data = np.array(img).astype(np.int8)

        # Flip Y: PGM has row 0 at top, OccupancyGrid has row 0 at bottom
        map_data = np.flipud(map_data)

        # Convert to ROS OccupancyGrid values (0=free, 100=occupied, -1=unknown)
        occ_data = np.where(map_data == 0, 100, 0).flatten().tolist()

        # Build message
        self.map_msg = OccupancyGrid()
        self.map_msg.header.frame_id = "map"
        self.map_msg.info.resolution = resolution
        self.map_msg.info.width = img.width
        self.map_msg.info.height = img.height
        self.map_msg.info.origin.position.x = origin[0]
        self.map_msg.info.origin.position.y = origin[1]
        self.map_msg.info.origin.position.z = origin[2]
        self.map_msg.info.origin.orientation.w = 1.0
        self.map_msg.data = occ_data

        # Publish at 2 Hz
        self.pub = node.create_publisher(OccupancyGrid, '/map', queue_size=1, transient_local=True)
        self.timer = node.create_timer(0.5, self.publish_map)
        node.loginfo("Map published: %dx%d @ %.2f m/px — waiting for goal...",
                     img.width, img.height, resolution)

    def publish_map(self):
        self.node.stamp_header(self.map_msg.header)
        self.pub.publish(self.map_msg)


if __name__ == '__main__':
    node = CompatNode('map_publisher')
    MapPublisher(node)
    spin(node)
